server:
  port: 7001

spring:
  application:
    name: wxsp-config-server
  profiles:
    active: native    #开启本地配置 默认为git
  cloud:
    config:
      server:
        native:
          search-locations: ../wxsp/wxsp-config-server/config-repo
# git管理配置
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/huxinsheng/wxsp
#          searchPaths: config-server/config-repo
#          username:  username
#          password:  password



